server:
  port: 8087
spring:
  security:
    cors:
      enable: true
  #    user:
  #      name: 2
  #      password: 2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tushu?useSSl=false
    username: root
    password: 123456
  redis:

#  web:
#    resources:
#      static-locations: file:${web.upLoadPath}
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #配置mp的底层执行语句输出 输出sql语句执行情况
  mapper-locations:
    - classpath:Mapper/*.xml
logging:
  level:
    org.springframework.security: DEBUG


